name: GCP Cloud Function  CI

on:
  workflow_dispatch:
    branches: [master]

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v2
      - id: Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SERVICE_KEY }}
      - id: Deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: "andateAF"
          runtime: "python39"
          secret_environment_variables: "TWITTER_ACCESS_TOKEN_KEY=projects/samser/secrets/TWITTER_ACCESS_TOKEN_KEY/versions/1 TWITTER_ACCESS_TOKEN_SECRET=projects/samser/secrets/TWITTER_ACCESS_TOKEN_SECRET/versions/1 TWITTER_API_KEY=projects/samser/secrets/TWITTER_API_KEY/versions/1 TWITTER_API_SECRET=projects/samser/secrets/TWITTER_API_SECRET/versions/1 TWITTER_BEARER_TOKEN=projects/samser/secrets/TWITTER_BEARER_TOKEN/versions/1"
